name: Frontend CI

on:
  push:
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (root)
        run: npm ci

      - name: Lint frontend
        run: npm run --workspace=frontend lint

      - name: Unit tests
        run: npm run --workspace=frontend test -- --run

      - name: Build frontend
        run: npm run --workspace=frontend build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: packages/frontend/dist 